#第三章汇总联系

apples=['iphone_x','ipad_pro','macbook_pro','imac_pro','apple_watch']
#字符串的方法：首字母大写、全部大写、全部小写
print(apples[0].title())
print(apples[1].lower())
print(apples[2].upper())
#字符串的方法：在末尾添加元素、在任意位置添加元素
apples.append('apple_pencil')
print(apples)
apples.insert(0,'ipod')
print(apples)
#字符串的方法：删除最后一个元素并使用、删除任意一个元素
last=apples.pop()
apples.remove('ipod')
print(last)
print(apples)
#字符串临时排序
print(sorted(apples))
print(apples)
#字符串永久排序
apples.sort()
print(apples)
#字符串的长度
print(len(apples))